### PR TITLE
Modulenames try3

### PR DESCRIPTION
**Pull request by tst2005**
Yet another try to move each l2l parts into a l2l directory (and use `l2l.core` module name instead of `core` one)
I partially disable the prefix name detection.
Most of samples are ok.

### CODE REVIEW

**Comment by meric** [comment]
Looks good so far. I'll take a closer look soon. I think I'll add back the symlink though, it was cool, or just make a plain ./l2l script with the hash bang at the top.

**Comment by tst2005** [comment]
I suggest to add a `bin/l2l` symlink to ../l2l/core.lua

```
export PATH="$PATH:bin"
l2l sample01.lsp
```
or withtout PATH change
```
./bin/l2l sample01.lsp
```

**Comment by meric** [comment]
Ahh, it's in the `bin` folder.

**Comment by meric** [comment]
Thanks!

**Comment by meric** [comment]
It feels a lot more encapsulated.

**Pull request merged**
