### PR TITLE
Modules names

### PR DESCRIPTION
**Pull request by tst2005**
All `l2l` components are prefixed by `l2l.*` to avoid conflict with other lua modules.

### CODE REVIEW

**Comment by meric** [comment]
How should the conflicts be merged?

**Comment by tst2005** [comment]
My change change the way to call `l2l`.
all components must be called with `require "l2l.SOMETHING"` instead of `require "SOMETHING"`
See the change for [sample01.lua](https://github.com/tst2005/l2l/commit/8db6a9384e05e6066e5cd99dd68ba7294e959383#diff-6346c8b534f3d1dc13323339efda9cb7R12)
but the `l2l` module it-self is still available with `require "l2l"` or `require "l2l.init"` or `require "l2l.core"`


... but maybe you ask about a git merge conflict ... I just see the `This branch has conflicts that must be resolved` message.

**Comment by meric** [comment]
Yes, the git conflict. Are you able to rebase on master?

**Comment by tst2005** [comment]
The https://github.com/meric/l2l/pull/11 touch the same goal differently.

My approach was to : 
 * move All module parts (`core.lua`, `import.lua`, `itertools.lua`, etc.) inside a new `l2l/` directory.
 * use and call static name like `l2l.core`, `l2l.import`, `l2l.itertools`, etc.
 * the loading issue must be solved over the package.path

If you also need a standalone executable binary ...

**Comment by tst2005** [comment]
A new try was done [here](https://github.com/meric/l2l/pull/22).

**Pull request closed without merging**
